server {
    listen 80;
    server_name 192.168.0.108; # IP da sua VM

    # 1. FRONTEND (React Estático)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # Suporte às rotas do React Router
    }

    # 2. BACKEND (API Django)
    location /api/ {
        proxy_pass http://web:8000; # Nome do serviço no docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 3. DJANGO ADMIN E STATIC (Imagens/CSS do Admin)
    location /admin/ {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
    }

    location /static/ {
        alias /app/static/; # Onde o Django coloca os arquivos do Admin
    }
}
