# Generated by Django 4.2.28 on 2026-03-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraEnergia',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('sensor_id', models.TextField()),
                ('tensao', models.FloatField()),
                ('corrente', models.FloatField()),
                ('potencia', models.FloatField()),
                ('consumo', models.FloatField()),
            ],
            options={
                'db_table': 'leitura_energia',
                'managed': True,
            },
        ),
    ]
